<?php

use yii\db\Migration;

/**
 * Class m200831_181117_add_codigo_postal
 */
class m200831_181117_add_codigo_postal extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'AGUADA CECILIO']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'AGUADA DE CORDOBA']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'AGUADA DE GUANACO']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'AGUADA DE GUERRA']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'AGUADA DEL LORO']);
        $this->update('localidad',['codigo_postal'=>8301], ['upper(nombre)' =>'AGUADA DE LOS PAJARITOS']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'AGUADA DE PIEDRA']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'AGUADA ESCONDIDA']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'AGUADA GUZMAN']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'AGUADA TRONCOSO (EMBARCADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'AGUA DEL CERRO']);
        $this->update('localidad',['codigo_postal'=>8307], ['upper(nombre)' =>'AGUARA']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'ALANITOS']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'ALEJANDRO STEFENELLI']);
        $this->update('localidad',['codigo_postal'=>8328], ['upper(nombre)' =>'ALLEN']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'ANECON CHICO']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'ANECON GRANDE']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'ANTIGUO GENERAL ROCA']);
        $this->update('localidad',['codigo_postal'=>8403], ['upper(nombre)' =>'ARROYO BLANCO']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'ARROYO CHACAY']);
        $this->update('localidad',['codigo_postal'=>8521], ['upper(nombre)' =>'ARROYO DE LA VENTANA']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'ARROYO LAS MINAS']);
        $this->update('localidad',['codigo_postal'=>8521], ['upper(nombre)' =>'ARROYO LOS BERROS']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'ARROYO MARTIN (ÑORQUINCO']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'ARROYO MARTIN (MAQUINCHAO']);
        $this->update('localidad',['codigo_postal'=>8532], ['upper(nombre)' =>'ARROYO SALADO']);
        $this->update('localidad',['codigo_postal'=>8521], ['upper(nombre)' =>'ARROYO TEMBRADO']);
        $this->update('localidad',['codigo_postal'=>8521], ['upper(nombre)' =>'ARROYO VERDE']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'ATRAICO']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'BAHIA LOPEZ']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'BAJO PICASO']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'BAJO RICO']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'BALNEARIO EL CONDOR']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'BALNEARIO LA BOCA']);
        $this->update('localidad',['codigo_postal'=>8521], ['upper(nombre)' =>'BALNEARIO LAS GRUTAS']);
        $this->update('localidad',['codigo_postal'=>8500], ['upper(nombre)' =>'BALNEARIO MASSINI']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'BARDA COLORADA']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'BARDA CHICA']);
        $this->update('localidad',['codigo_postal'=>8305], ['upper(nombre)' =>'BARDA DEL MEDIO']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'BARILOCHE']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'BARRIL NIYEO']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'BARRIO DON BOSCO']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'BARRIO LAGUNA']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'BARRIO LAS QUINTAS']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'BARRIO MATADEROS']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'BARRIO NIRECO']);
        $this->update('localidad',['codigo_postal'=>8328], ['upper(nombre)' =>'BARRIO NORTE']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'BARRIO TRESCIENTAS VIVIENDAS']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'BENJAMIN ZORRILLA']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'BLANCA CHICA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'BLANCA LOMA']);
        $this->update('localidad',['codigo_postal'=>8505], ['upper(nombre)' =>'BOCA DE LA TRAVESIA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'BUENA PARADA']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'BUENZANIYEU']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'CAIN']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'CALTRAUNA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'CAMPAMENTO']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'CAÑADA GRANDE']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'CAÑADON COMALLO']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'CAÑADON CHILENO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'CAÑADON DEL CORRAL']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'CAÑADON DE LOS SAUCES']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'CAÑADON TRINCAO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'CARHUE']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'CARRILAUQUEN']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'CARRI YEGUA']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'CASA QUEMADA']);
        $this->update('localidad',['codigo_postal'=>8307], ['upper(nombre)' =>'CATRIEL']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'CERRO ABANICO (APEADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8403], ['upper(nombre)' =>'CERRO ALTO']);
        $this->update('localidad',['codigo_postal'=>8505], ['upper(nombre)' =>'CERRO BARAJA']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'CERRO CATEDRAL']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'CERRO DAVID']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'CERRO DE LA POLICIA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'CERRO DE LOS VIEJOS']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'CERRO DE POLICIA']);
        $this->update('localidad',['codigo_postal'=>8505], ['upper(nombre)' =>'CERRO FRANCISCO']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'CERRO GALENSE']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'CERRO MESA']);
        $this->update('localidad',['codigo_postal'=>8326], ['upper(nombre)' =>'CERVANTES']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'CINCO CHAÑARES']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'CINCO LAGUNAS']);
        $this->update('localidad',['codigo_postal'=>8303], ['upper(nombre)' =>'CINCO SALTOS']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'CIPOLLETTI']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'CLEMENTE ONELLI']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'COLINIYEN']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'COLI TORO']);
        $this->update('localidad',['codigo_postal'=>8307], ['upper(nombre)' =>'COLONIA ALMIRANTE GUERRICO']);
        $this->update('localidad',['codigo_postal'=>8307], ['upper(nombre)' =>'COLONIA CATRIEL']);
        $this->update('localidad',['codigo_postal'=>8532], ['upper(nombre)' =>'COLONIA CHILAVERT']);
        $this->update('localidad',['codigo_postal'=>8305], ['upper(nombre)' =>'COLONIA EL MANZANO']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'COLONIA GRAL. FRIAS']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'COLONIA JOSEFA']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'LA CAROLINA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'LA COSTA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA CRIOLLITA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA CHILENA']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'LA ELVIRA']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'LA EMILIA']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'LA ESMERALDA (DARWIN']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'LA ESMERALDA (CIPOLLETTI']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'LA ESPERANZA']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'LA ESTANCIA VIEJA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA ESTRELLA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA EXCURRA']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'LA FLECHA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'LA GEROMITA']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'LAGO GUTIERREZ']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'LAGO MASCARDI']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'LAGO MORENO']);
        $this->update('localidad',['codigo_postal'=>8305], ['upper(nombre)' =>'LAGO PELLEGRINI']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'LA GRANJA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LAGUNA BLANCA']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'LAGUNA CORTES']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'LAGUNA DE LA PRUEBA']);
        $this->update('localidad',['codigo_postal'=>8514], ['upper(nombre)' =>'LAGUNA DEL BARRO']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'LAGUNA DEL CHASICO']);
        $this->update('localidad',['codigo_postal'=>8514], ['upper(nombre)' =>'LAGUNA DEL MONTE']);
        $this->update('localidad',['codigo_postal'=>8411], ['upper(nombre)' =>'LAGUNA FRIAS']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'LAGUNA GUANACO']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'LAGUNITA']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'LA JUANITA (DARWIN']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'LA JUANITA (RIO COLORADO']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'LA JULIA']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'LA LUCINDA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'LA LUNA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'LA MARIA INES']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'LAMARQUE']);
        $this->update('localidad',['codigo_postal'=>8500], ['upper(nombre)' =>'LA MESETA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA MIMOSA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'LA MONTAÑESA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LANQUIÑEO']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'LA PAMPA']);
        $this->update('localidad',['codigo_postal'=>8303], ['upper(nombre)' =>'LA PICASA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA PORTEÑA']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'LA PRIMAVERA']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'LA QUEBRADA']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'LA RINCONADA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA RUBIA']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'LA SARA']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'LAS BAYAS']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'LAS GRUTAS']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'LA SIN BOMBO']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'LAS MAQUINAS']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LAS MELLIZAS']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'LAS MOCHAS']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'LAS ÑATITAS']);
        $this->update('localidad',['codigo_postal'=>8366], ['upper(nombre)' =>'LA TEODOLINA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA VENCEDORA']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'LANZANIYEN']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'LIPETREN']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'LOMA BLANCA']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'LOMA PARTIDA']);
        $this->update('localidad',['codigo_postal'=>8411], ['upper(nombre)' =>'LOS CANTAROS']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LOS COSTEROS']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'LOS JUNCOS (DPTO. PILCANIYEU)']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'LOS JUNCOS (APEADERO FCGR) (MAQUINCHAO']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'LOS MANANTIALES']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'LOS MENUCOS (DPTO. 25 DE MAYO)']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'LOS MOLINOS']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LOS PIRINEOS']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LOS QUEBRACHOS']);
        $this->update('localidad',['codigo_postal'=>8430], ['upper(nombre)' =>'LOS REPOLLOS']);
        $this->update('localidad',['codigo_postal'=>8307], ['upper(nombre)' =>'LOS SAUCES']);
        $this->update('localidad',['codigo_postal'=>8361], ['upper(nombre)' =>'LUIS BELTRAN']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'LUIS M. ZAGAGLIA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'LUPAY NIYEO']);
        $this->update('localidad',['codigo_postal'=>8409], ['upper(nombre)' =>'LLAO LLAO']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'MACACHIN']);
        $this->update('localidad',['codigo_postal'=>8326], ['upper(nombre)' =>'MAINQUE']);
        $this->update('localidad',['codigo_postal'=>8430], ['upper(nombre)' =>'MALLIN AHOGADO']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'MAMUEL CHOIQUE']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'MANCULLIQUE']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'MANCHA BLANCA']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'MAQUINCHAO']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'MARI LAUQUEN']);
        $this->update('localidad',['codigo_postal'=>8500], ['upper(nombre)' =>'MATA NEGRA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'MEDIA LUNA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'MENCUE']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'MENUCO NEGRO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'MENUCO VACA MUERTA']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'MICHI HONOCA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'MICHIHUAO']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'MINISTRO RAMOS MEXIA']);
        $this->update('localidad',['codigo_postal'=>8366], ['upper(nombre)' =>'MIRA PAMPA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'COLONIA JULIA Y ECHARREN']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'COLONIA LA LUISA']);
        $this->update('localidad',['codigo_postal'=>8316], ['upper(nombre)' =>'COLONIA LOS CANALES']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'COLONIA REGINA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'COLONIA RUSA']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'COLONIA SAN JUAN']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'COLONIA SUIZA']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'COMALLO']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'COMALLO ABAJO']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'COMI-C']);
        $this->update('localidad',['codigo_postal'=>8521], ['upper(nombre)' =>'CONA NIYEU']);
        $this->update('localidad',['codigo_postal'=>8301], ['upper(nombre)' =>'CONTRALMIRANTE CORDERO']);
        $this->update('localidad',['codigo_postal'=>8328], ['upper(nombre)' =>'CONTRALMIRANTE MARTIN GUERRICO']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'COQUELEN']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'CORONEL BELISLE']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'CORONEL EUGENIO DEL BUSTO']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'CORONEL FRANCISCO SOSA (EMBARCADRO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'CORONEL JUAN JOSE GOMEZ']);
        $this->update('localidad',['codigo_postal'=>8305], ['upper(nombre)' =>'CORONEL VIDAL']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'CORRAL CHICO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'CORRAL DE LOS PINOS']);
        $this->update('localidad',['codigo_postal'=>8403], ['upper(nombre)' =>'CORRALITO']);
        $this->update('localidad',['codigo_postal'=>8430], ['upper(nombre)' =>'COSTA DEL RIO AZUL']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'COSTAS DEL PICHI LEUFU']);
        $this->update('localidad',['codigo_postal'=>8307], ['upper(nombre)' =>'COS ZAURES']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'COYUE CO']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'CUATRO ESQUINAS']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'CUBANEA']);
        $this->update('localidad',['codigo_postal'=>8301], ['upper(nombre)' =>'CUENCA VIDAL']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'CURA LAUQUEN']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'CUYEN-LEUFU']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'CHACALHUA RUCA']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'CHACAY HUARRUCA']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'CHACOY (BRACA)']);
        $this->update('localidad',['codigo_postal'=>8328], ['upper(nombre)' =>'CHACRAS DE ALLEN']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'CHAIFUL']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'CHASICO']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'CHAUQUEN']);
        $this->update('localidad',['codigo_postal'=>8366], ['upper(nombre)' =>'CHELFORO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'CHENQUENIYEU']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'CHICHIHUAO']);
        $this->update('localidad',['codigo_postal'=>8326], ['upper(nombre)' =>'CHICHINALES']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'CHIMPAY']);
        $this->update('localidad',['codigo_postal'=>8504], ['upper(nombre)' =>'CHINA MUERTA']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'CHINQUENIYEU']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'CHIPAUQUIL']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'CHOCORI']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'CHOELE CHOEL']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'CHURQUIÑEO']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'DARWIN']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'DOCTOR ROGELIO CORTIZO (EMPALME)']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'DON GUILLERMO']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'EL AGUILA']);
        $this->update('localidad',['codigo_postal'=>8430], ['upper(nombre)' =>'EL BOLSON']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'EL CACIQUE']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'EL CAIN']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'EL CALDEN']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'EL CAMARURO']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'EL CUY']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'EL CHEIFUL']);
        $this->update('localidad',['codigo_postal'=>8500], ['upper(nombre)' =>'EL DIQUE']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'EL FOYEL']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'EL GAUCHO POBRE']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'EL HINOJO']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'EL JARDINERO']);
        $this->update('localidad',['codigo_postal'=>8430], ['upper(nombre)' =>'EL MANSO']);
        $this->update('localidad',['codigo_postal'=>8328], ['upper(nombre)' =>'EL MANZANO']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'EL MIRADOR']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'EL MOLIGUE']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'EL MOLINO']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'EL MONTOSO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'EL PANTANOSO']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'EL SALADO']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'EL TREBOL']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'EMPALME DOCTOR ROGELIO CORTISO']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'EMPALME KILOMETRO 648 (APEADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'ESTANCIA EL CONDOR']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'ESTANCIA LAS JULIAS']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'FALCKNER']);
        $this->update('localidad',['codigo_postal'=>8301], ['upper(nombre)' =>'FERRI']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'FITALANCAO (EMBARCADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'FITAMICHE']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'FITATIMEN']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'FORTIN UNO']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'FUERTE GENERAL ROCA']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'FUERTE RUIN (EMBARCADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'GARZU LAUQUEN (APEADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'GARRAS']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'GENERAL CONESA']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'GENERAL ENRIQUE GODOY']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'GENERAL FERNANDEZ ORO']);
        $this->update('localidad',['codigo_postal'=>8500], ['upper(nombre)' =>'GENERAL LIBORIO BERNAL']);
        $this->update('localidad',['codigo_postal'=>8514], ['upper(nombre)' =>'GENERAL LORENZO VINTTER']);
        $this->update('localidad',['codigo_postal'=>8514], ['upper(nombre)' =>'GENERAL NICOLAS H. PALACIOS']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'GENERAL ROCA']);
        $this->update('localidad',['codigo_postal'=>8505], ['upper(nombre)' =>'GUARDIA MITRE']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'HOTEL BAHIA LOPEZ']);
        $this->update('localidad',['codigo_postal'=>8409], ['upper(nombre)' =>'HOTEL EL TREBOL']);
        $this->update('localidad',['codigo_postal'=>8409], ['upper(nombre)' =>'HOTEL ENTRE LAGOS']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'HOTEL LOS COIHUES']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'HUA-MICHE']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'MONTE BAGUAL']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'MONTE REDONDO']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'MULANILLO']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'MUSTERS']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'NAHUEL NIYEU']);
        $this->update('localidad',['codigo_postal'=>8313], ['upper(nombre)' =>'NAUPA HUEN']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'NEGRO MUERTO']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'NENEO RUCA (ESTACION FCGR)']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'NILUAN']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'NIRIHUAO (ESTACION FCGR)']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'NITRALA MACOHUE']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'NUEVA CAROLINA']);
        $this->update('localidad',['codigo_postal'=>8514], ['upper(nombre)' =>'NUEVO LEON']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'ÑIRIHUAO']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'ÑORQUINCO']);
        $this->update('localidad',['codigo_postal'=>8409], ['upper(nombre)' =>'OJOS DE AGUA (LLAO LLAO']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'OJOS DE AGUA (EMBARC. FCGR']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'PADRE ALEJANDRO STEFENELLI']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'PAJALTA (APEADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'PALENQUE NIYEU']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'PANQUEHUAO']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'PASO CORDOVA']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'PASO CHACABUCO']);
        $this->update('localidad',['codigo_postal'=>8403], ['upper(nombre)' =>'PASO DEL LIMAY']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'PASO DE LOS MOLLES']);
        $this->update('localidad',['codigo_postal'=>8403], ['upper(nombre)' =>'PASO FLORES']);
        $this->update('localidad',['codigo_postal'=>8361], ['upper(nombre)' =>'PASO LEZCANO']);
        $this->update('localidad',['codigo_postal'=>8403], ['upper(nombre)' =>'PASO MIRANDA']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'PASO PEÑALVA']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'PASO PIEDRA']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'PATU CO']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'PENINSULA HUEMUL']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'PENINSULA SAN PEDRO']);
        $this->update('localidad',['codigo_postal'=>8307], ['upper(nombre)' =>'PEÑAS BLANCAS']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'PERCY H. SCOTT (APEADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'PERITO MORENO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'PICHI LEUFU (APEADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'PICHI LEUFU ABAJO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'PICHI LEUFU ARRIBA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'PICHI MAHUIDA']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'PIEDRA BLANCA (SAN CARLOS DE BARILOCHE']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'PIEDRA BLANCA (GRAL. ROCA']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'PIEDRA CLAVADA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'PILAHUE']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'PILCANIYEU']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'PILCANIYEU VIEJO']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'PLANICIE DE JAGUELITO']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'PLAYA BONITA']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'POMONA']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'PORTEZUELO']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'POZO MORO']);
        $this->update('localidad',['codigo_postal'=>8514], ['upper(nombre)' =>'POZO SALADO']);
        $this->update('localidad',['codigo_postal'=>8424], ['upper(nombre)' =>'PRAHUANIYEU']);
        $this->update('localidad',['codigo_postal'=>8505], ['upper(nombre)' =>'PRIMERA ANGOSTURA']);
        $this->update('localidad',['codigo_postal'=>8505], ['upper(nombre)' =>'PRONUNCIAMIENTO']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'PUEBLO VIEJO']);
        $this->update('localidad',['codigo_postal'=>8411], ['upper(nombre)' =>'PUERTO BLEST']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'PUERTO HERMOSO']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'PUERTO MORENO']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'PUERTO OJO DE AGUA']);
        $this->update('localidad',['codigo_postal'=>8409], ['upper(nombre)' =>'PUERTO PAÑUELO']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'PUERTO PICHI MAHUIDA']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'PUERTO SANTA MARIA']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'PUERTO TIGRE']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'PUESTO FARIA']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'PUESTO GAVIÑA']);
        $this->update('localidad',['codigo_postal'=>8356], ['upper(nombre)' =>'PUNTA DE AGUA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'QUEMPU NIYEU']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'QUETREQUILE']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'QUINIÑAU']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'QUINTA PANAL']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'QUO VADIS']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'RAYHUAO']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'REPOLLOS']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'RINCONADA']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'RINCON DE GASTRE']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'RIO COLORADO']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'RIO CHICO']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'RIO NIRIHUANO']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'RIO VILLEGAS']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'RIVADAVIA']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'RUCU LUAN']);
        $this->update('localidad',['codigo_postal'=>8500], ['upper(nombre)' =>'RUTA 3 KILOMETRO 974']);
        $this->update('localidad',['codigo_postal'=>8514], ['upper(nombre)' =>'SACO VIEJO']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'SALITRAL NEGRO']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'SAN ANTONIO DEL CUY']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'SAN ANTONIO OESTE']);
        $this->update('localidad',['codigo_postal'=>8400], ['upper(nombre)' =>'SAN CARLOS DE BARILOCHE']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'SAN CAYETANO']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'SAN EDUARDO']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'SAN JAVIER']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'SAN JORGE']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'SAN JOSE DE PAJA ALTA']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'SAN JUAN (GRAL. CONESA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'SAN JUAN (RIO COLORADO']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'SAN LEON']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'SAN LORENZO']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'SAN PABLO']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'HUAN LUAN']);
        $this->update('localidad',['codigo_postal'=>8415], ['upper(nombre)' =>'HURRACA (CHACAY)']);
        $this->update('localidad',['codigo_postal'=>8334], ['upper(nombre)' =>'INGENIERO HUERGO']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'INGENIERO JACOBACCI']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'INGENIERO JULIAN ROMERO']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'INGENIERO OTTO KRAUSE']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'INGENIERO ZIMMERMANN RESTA (APEADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'INGENIO SAN LORENZO']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'ISLA CHICA']);
        $this->update('localidad',['codigo_postal'=>8361], ['upper(nombre)' =>'ISLA GRANDE']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'JAGUEL CAMPO MONTE']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'JANINUE']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'JITA RUSIA']);
        $this->update('localidad',['codigo_postal'=>8506], ['upper(nombre)' =>'JONES']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'JUAN DE GARAY']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'KILI MALAL']);
        $this->update('localidad',['codigo_postal'=>8134], ['upper(nombre)' =>'KILOMETRO 823']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'KILOMETRO 1071']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'KILOMETRO 1099']);
        $this->update('localidad',['codigo_postal'=>8305], ['upper(nombre)' =>'KILOMETRO 1218']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'LA ADELA']);
        $this->update('localidad',['codigo_postal'=>8324], ['upper(nombre)' =>'LA ALIANZA']);
        $this->update('localidad',['codigo_postal'=>9138], ['upper(nombre)' =>'LA AMISTAD']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'LA ANGOSTURA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'LA BALSA']);
        $this->update('localidad',['codigo_postal'=>8520], ['upper(nombre)' =>'LA BOMBILLA']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'SAN PEDRO (RIO COLORADO']);
        $this->update('localidad',['codigo_postal'=>8412], ['upper(nombre)' =>'SAN PEDRO (PILCANIYEU']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'SAN RAMON']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'SAN SIMON']);
        $this->update('localidad',['codigo_postal'=>8138], ['upper(nombre)' =>'SANTA ANA']);
        $this->update('localidad',['codigo_postal'=>8417], ['upper(nombre)' =>'SANTA ELENA']);
        $this->update('localidad',['codigo_postal'=>8363], ['upper(nombre)' =>'SANTA GENOVEVA']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'SANTA GREGORIA']);
        $this->update('localidad',['codigo_postal'=>8366], ['upper(nombre)' =>'SANTA JULIA']);
        $this->update('localidad',['codigo_postal'=>8364], ['upper(nombre)' =>'SANTA NICOLASA']);
        $this->update('localidad',['codigo_postal'=>8505], ['upper(nombre)' =>'SAUCE BLANCO (GUARDIA MITRE']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'SAUCE BLANCO (CHOELE CHOEL']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'SEGUNDA ANGOSTURA']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'SIERRA BLANCA']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'SIERRA COLORADA']);
        $this->update('localidad',['codigo_postal'=>8521], ['upper(nombre)' =>'SIERRA DE LA VENTANA']);
        $this->update('localidad',['codigo_postal'=>8532], ['upper(nombre)' =>'SIERRA GRANDE']);
        $this->update('localidad',['codigo_postal'=>8521], ['upper(nombre)' =>'SIERRA PAILEMAN']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'TALCAHUALA (APEADERO FCGR)']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'TAPILUQUE']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'TENIENTE GRAL. EUSTAQUIO FRIAS']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'TENIENTE MAZA (ESTACION FCGR)']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'TERCERA ZONA']);
        $this->update('localidad',['codigo_postal'=>8360], ['upper(nombre)' =>'TRAGUA TRAGUA']);
        $this->update('localidad',['codigo_postal'=>8503], ['upper(nombre)' =>'TRAVESIA CASTRO']);
        $this->update('localidad',['codigo_postal'=>8333], ['upper(nombre)' =>'TRECA-CO']);
        $this->update('localidad',['codigo_postal'=>8534], ['upper(nombre)' =>'TRENETA']);
        $this->update('localidad',['codigo_postal'=>8416], ['upper(nombre)' =>'TRES OJOS DE AGUA']);
        $this->update('localidad',['codigo_postal'=>8332], ['upper(nombre)' =>'TRICACO']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'TROMENIYEU']);
        $this->update('localidad',['codigo_postal'=>8409], ['upper(nombre)' =>'TUNKELEN']);
        $this->update('localidad',['codigo_postal'=>8422], ['upper(nombre)' =>'VACA LAUQUEN']);
        $this->update('localidad',['codigo_postal'=>8536], ['upper(nombre)' =>'VALCHETA']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'VALLE AZUL']);
        $this->update('localidad',['codigo_postal'=>8307], ['upper(nombre)' =>'VALLE DE LOS ALAMOS']);
        $this->update('localidad',['codigo_postal'=>8514], ['upper(nombre)' =>'VICEALMIRANTE EDUARDO O’CONNOR (ESTACION FCGR)']);
        $this->update('localidad',['codigo_postal'=>8500], ['upper(nombre)' =>'VIEDMA']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'VILLA ALBERDI']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'VILLA LLANQUIN']);
        $this->update('localidad',['codigo_postal'=>8401], ['upper(nombre)' =>'VILLA MASCARDI']);
        $this->update('localidad',['codigo_postal'=>8336], ['upper(nombre)' =>'VILLA REGINA']);
        $this->update('localidad',['codigo_postal'=>8430], ['upper(nombre)' =>'VILLA TURISMO']);
        $this->update('localidad',['codigo_postal'=>8418], ['upper(nombre)' =>'YUQUINCHE']);
        $this->update('localidad',['codigo_postal'=>8501], ['upper(nombre)' =>'ZANJON DE OYUELA']);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m200831_181117_add_codigo_postal cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m200831_181117_add_codigo_postal cannot be reverted.\n";

        return false;
    }
    */
}
