<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "departamento".
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $provinciaid
 *
 * @property \app\models\Provincia $provincia
 * @property \app\models\Localidad[] $localidads
 * @property string $aliasModel
 */
abstract class Departamento extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'departamento';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['provinciaid'], 'integer'],
            [['nombre'], 'string', 'max' => 300],
            [['provinciaid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Provincia::className(), 'targetAttribute' => ['provinciaid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'provinciaid' => 'Provinciaid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvincia()
    {
        return $this->hasOne(\app\models\Provincia::className(), ['id' => 'provinciaid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocalidads()
    {
        return $this->hasMany(\app\models\Localidad::className(), ['departamentoid' => 'id']);
    }




}
