<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "localidad".
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $regionid
 * @property integer $departamentoid
 * @property integer $municipioid
 *
 * @property \app\models\Departamento $departamento
 * @property \app\models\Municipio $municipio
 * @property \app\models\Region $region
 * @property \app\models\Lugar[] $lugars
 * @property string $aliasModel
 */
abstract class Localidad extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'localidad';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['regionid', 'departamentoid', 'municipioid'], 'integer'],
            [['nombre'], 'string', 'max' => 200],
            [['departamentoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Departamento::className(), 'targetAttribute' => ['departamentoid' => 'id']],
            [['municipioid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Municipio::className(), 'targetAttribute' => ['municipioid' => 'id']],
            [['regionid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Region::className(), 'targetAttribute' => ['regionid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'regionid' => 'Regionid',
            'departamentoid' => 'Departamentoid',
            'municipioid' => 'Municipioid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartamento()
    {
        return $this->hasOne(\app\models\Departamento::className(), ['id' => 'departamentoid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMunicipio()
    {
        return $this->hasOne(\app\models\Municipio::className(), ['id' => 'municipioid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegion()
    {
        return $this->hasOne(\app\models\Region::className(), ['id' => 'regionid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLugars()
    {
        return $this->hasMany(\app\models\Lugar::className(), ['localidadid' => 'id']);
    }




}
