<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "localidad_extra".
 *
 * @property integer $localidadid
 *
 * @property \app\models\Localidad $localidad
 * @property string $aliasModel
 */
abstract class LocalidadExtra extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'localidad_extra';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['localidadid'], 'required'],
            [['localidadid'], 'integer'],
            [['localidadid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Localidad::className(), 'targetAttribute' => ['localidadid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'localidadid' => 'Localidadid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocalidad()
    {
        return $this->hasOne(\app\models\Localidad::className(), ['id' => 'localidadid']);
    }




}
